### ISSUE TITLE
optional chaining problem

### ISSUE THREAD

**Issue by laurib** [davidje13/neutrino-typescript-react-example#1]
```
/node_modules/typescript-eslint-converter/index.js:52
        options.baseConfig?.extends,
                           ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
```

your repo code + npm update

**Comment by davidje13** [comment]
I can't replicate this error.

Running `npm update` changes the package.json dependencies to the following:

```
  "dependencies": {
    "react": "^16.14.0",
    "react-dom": "^16.14.0"
  },
  "devDependencies": {
    "@neutrinojs/eslint": "9.x",
    "@neutrinojs/jest": "9.x",
    "@neutrinojs/node": "9.x",
    "@neutrinojs/react": "9.x",
    "@testing-library/react": "^11.1.0",
    "@types/jest": "^26.0.15",
    "@types/react": "^16.9.55",
    "@types/react-dom": "^16.9.9",
    "eslint": "^7.12.1",
    "eslint-plugin-react": "^7.21.5",
    "jest": "^26.6.1",
    "neutrino": "9.x",
    "neutrinojs-typescript": "^1.1.5",
    "neutrinojs-typescript-eslint": "1.x",
    "typescript": "^4.0.5",
    "webpack": "^4.44.2",
    "webpack-cli": "3.x",
    "webpack-dev-server": "3.x"
  }
```

And all the commands listed in the readme still work fine and the site renders correctly. I also tried deleting the package-lock.json entirely and reinstalling dependencies, which was also fine.

Can you post which version of nodejs you are running, which exact command caused the error (and where), and if your resulting package.json is different to the above please post that too. Do you get the same error from a fresh checkout if you don't do an `npm update`?

**Comment by davidje13** [comment]
Looking a bit deeper, I suspect you're using an old version of NodeJS. The `?.` syntax was added in 14 (the current LTS version).

I can probably fix that specific location to work in older versions of node, but I'm not really supporting anything except latest & latest LTS versions. So you might hit other problems. It looks like core Neutrino [supports NodeJS 10 and 14](https://github.com/neutrinojs/neutrino/blob/master/.travis.yml#L4) right now.

If it's possible for you to upgrade to version 14 or 15 of node, I suggest doing that. Otherwise I can try to downgrade the syntax used in these projects but I can't guarantee it will work / will continue to work.

**Comment by davidje13** [comment]
I split out https://github.com/davidje13/typescript-eslint-converter/issues/1 and that package now supports NodeJS 10, 12, 14 and 15.

I don't know if that will fix your issue but it should get you past at least this particular error. As I said, best solution is for you to upgrade to a recent version of NodeJS.

**Comment by davidje13** [comment]
Closing this since I haven't heard anything for a couple of weeks. Feel free to reopen if you still have problems with the latest version.
